export const resList = [
    {
      info: {
        id: "523613",
        name: "Mcdondles",
        cloudinaryImageId: "03501c33ecb3a3105124441e541e6fe4",
        locality: "Lulu Mall",
        areaName: "LuLu Mall",
        costForTwo: "₹350 for two",
        cuisines: ["Mcdondles", "Burger"],
        avgRating: 3.3,
        parentId: "166",
        avgRatingString: "3.3",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 40,
          lastMileTravel: 3.6,
          serviceability: "SERVICEABLE",
          slaString: "40-45 mins",
          lastMileTravelString: "3.6 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-27 23:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "70% OFF",
          subHeader: "UPTO ₹100",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-ce70cd13-b2b2-4df6-ac35-7f65ac4e02a0",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/burger-king-lulu-mall-thiruvananthapuram-523613",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "429782",
        name: "Oven story",
        cloudinaryImageId: "nfrkux2t6otpiu2irsod",
        locality: "lucky Mall",
        areaName: "Kumarapuram",
        costForTwo: "₹150 for two",
        cuisines: ["Pizzas"],
        avgRating: 3.2,
        parentId: "721",
        avgRatingString: "4.3",
        totalRatingsString: "500+",
        sla: {
          deliveryTime: 38,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "35-40 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-27 23:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "60% OFF",
          subHeader: "UPTO ₹120",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-ce70cd13-b2b2-4df6-ac35-7f65ac4e02a0",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/pizza-hut-lulu-mall-kumarapuram-thiruvananthapuram-429782",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "454138",
        name: "seashell",
        cloudinaryImageId: "mioi0p4orhzvwlvyqr7h",
        locality: "Kochuveli",
        areaName: "Kumarapuram",
        costForTwo: "₹800 for two",
        cuisines: [
          "Fish",
          "Crab",
          "Prawns",
          "parrotta",
        
        ],
        avgRating: 4.4,
        parentId: "195515",
        avgRatingString: "4.4",
        totalRatingsString: "500+",
        sla: {
          deliveryTime: 31,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-27 23:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "UPTO ₹50",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-ce70cd13-b2b2-4df6-ac35-7f65ac4e02a0",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/starbucks-coffee-kochuveli-kumarapuram-thiruvananthapuram-454138",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "433683",
        name: "Shri Mittai",
        cloudinaryImageId: "cxmaeqlyleysefcdx9nk",
        locality: "Janatha Business Centre",
        areaName: "Kazhakkoottam",
        costForTwo: "₹200 for two",
        cuisines: ["Chats", "badam Milk", "Dosa", "Idly"],
        avgRating: 4.2,
        veg: true,
        parentId: "19",
        avgRatingString: "4.2",
        totalRatingsString: "100+",
        sla: {
          deliveryTime: 58,
          lastMileTravel: 10.1,
          serviceability: "SERVICEABLE",
          slaString: "55-60 mins",
          lastMileTravelString: "10.1 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-27 21:30:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-ce70cd13-b2b2-4df6-ac35-7f65ac4e02a0",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/7th-heaven-janatha-business-centre-kazhakkoottam-thiruvananthapuram-433683",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "751799",
        name: "TaiBha",
        cloudinaryImageId: "6930b7784a753e0132370a95ce3b64a1",
        locality: "Venpalavattom",
        areaName: "Technopark",
        costForTwo: "₹200 for two",
        cuisines: ["Briyani", "Rice"],
        veg: true,
        parentId: "66374",
        avgRatingString: "NEW",
        sla: {
          deliveryTime: 23,
          lastMileTravel: 0.3,
          serviceability: "SERVICEABLE",
          slaString: "20-25 mins",
          lastMileTravelString: "0.3 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-27 19:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        isNewlyOnboarded: true,
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-ce70cd13-b2b2-4df6-ac35-7f65ac4e02a0",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/crumbs-venpalavattom-technopark-thiruvananthapuram-751799",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    
  ];